apiVersion: v1
kind: Pod
metadata:
  name: ibankingsafepod
  labels:
    app: ibanking
    version: "1.0"
spec:
  containers:
    - name: ibanking
      image: techsriman/inetbanking:1.0
      ports:
        - name: http
          containerPort: 8082
          protocol: TCP
      env:
        - name: "db.username"
          valueFrom:
            secretKeyRef:
              name: ibankingsafesecret
              key: username
        - name: "db.password"
          valueFrom:
            secretKeyRef:
              name: ibankingsafesecret
              key: password         
      volumeMounts:
        - name: ibankingvolume
          mountPath: /u01/app         
  volumes:
    - name: ibankingvolume
      persistenceVolumeClaim:
        claimName: ibankingpvc